/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto3_ed_fabianjeremmyritxiel;
//
import javax.swing.JOptionPane;



/**
 *
 * @author ritxi
 */
public class VentanaMercado extends javax.swing.JFrame {
    VentanaJugador ventJug;

    /**
     * Creates new form VentanaMercado
     */
    public VentanaMercado(VentanaJugador ventTemp) {
        this.ventJug = ventTemp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    private void insuficienteDinero(String nombre) {
        String mensaje = "No tiene suficiente dinero para comprar " + nombre;
        JOptionPane.showMessageDialog(null, mensaje, "Fondos insuficientes", JOptionPane.ERROR_MESSAGE);
    
    }
    private void insuficienteProducto(String nombre) {
    String mensaje = "No tiene suficiente producto para comprar " + nombre;
    JOptionPane.showMessageDialog(null, mensaje, "Cantidad insuficiente", JOptionPane.ERROR_MESSAGE);
}

    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton14 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnComprarHierro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnComprarBarcos = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnComprarCanon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnComprarCanonM = new javax.swing.JButton();
        btnComprarBomba = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnComprarCanonBB = new javax.swing.JButton();
        btnComprarMina = new javax.swing.JButton();
        btnComprarTemplo = new javax.swing.JButton();
        btnComprarArmeria = new javax.swing.JButton();
        btnComprarFuente = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        jButton14.setText("jButton14");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setText("Mercado");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Hierro");

        btnComprarHierro.setText("Comprar");
        btnComprarHierro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarHierroActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Barcos");

        btnComprarBarcos.setText("Comprar");
        btnComprarBarcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarBarcosActionPerformed(evt);
            }
        });

        jButton5.setText("Comprar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Cañon");

        btnComprarCanon.setText("Comprar");
        btnComprarCanon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarCanonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Cañon Múltiple");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Bomba");

        btnComprarCanonM.setText("Comprar");
        btnComprarCanonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarCanonMActionPerformed(evt);
            }
        });

        btnComprarBomba.setText("Comprar");
        btnComprarBomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarBombaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Cañón Barba Roja");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("Mina");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("Templo De la Bruja");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel10.setText("Armería");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel11.setText("Fuentes de energía");

        btnComprarCanonBB.setText("Comprar");
        btnComprarCanonBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarCanonBBActionPerformed(evt);
            }
        });

        btnComprarMina.setText("Comprar");
        btnComprarMina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarMinaActionPerformed(evt);
            }
        });

        btnComprarTemplo.setText("Comprar");
        btnComprarTemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarTemploActionPerformed(evt);
            }
        });

        btnComprarArmeria.setText("Comprar");
        btnComprarArmeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarArmeriaActionPerformed(evt);
            }
        });

        btnComprarFuente.setText("Comprar");
        btnComprarFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarFuenteActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel12.setText("Mercado");

        jButton2.setText("Vender");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Vender");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Vender");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Vender");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Vender");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Vender");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Vender");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Vender");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Vender");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Vender");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Vender");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel13.setText("$5");

        jLabel14.setText("$2500");

        jLabel15.setText("$500");

        jLabel16.setText("$700");

        jLabel17.setText("$700");

        jLabel18.setText("$1000");

        jLabel19.setText("$2500");

        jLabel20.setText("$1500");

        jLabel21.setText("$12000");

        jLabel22.setText("$2000");

        jLabel23.setText("$900");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel14)
                            .addGap(32, 32, 32)
                            .addComponent(btnComprarBarcos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton3)
                            .addGap(6, 6, 6))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(20, 20, 20)))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnComprarHierro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnComprarCanon)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnComprarBomba)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton7))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnComprarCanonM)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton6))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnComprarCanonBB)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton8))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(jLabel16))))
                .addGap(0, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGap(71, 71, 71)
                        .addComponent(btnComprarMina)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addComponent(jLabel21))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnComprarTemplo)
                                .addGap(18, 18, 18)
                                .addComponent(jButton10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnComprarArmeria)
                                .addGap(18, 18, 18)
                                .addComponent(jButton11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnComprarFuente))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton13)
                                    .addComponent(jButton12))))))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(btnComprarHierro)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnComprarBarcos)
                            .addComponent(jLabel3)
                            .addComponent(jButton3)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel15))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnComprarCanon)
                                .addComponent(jButton4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnComprarCanonM)
                                .addComponent(jButton6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(btnComprarBomba)
                            .addComponent(jButton7)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnComprarCanonBB)
                            .addComponent(jButton8)
                            .addComponent(jLabel23)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel19))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel21))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel22))
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel18))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnComprarMina)
                                        .addComponent(jButton9)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnComprarTemplo)
                                    .addComponent(jButton10))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnComprarArmeria)
                                    .addComponent(jButton11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnComprarFuente)
                                    .addComponent(jButton12)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton5)
                                    .addComponent(jButton13))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //VentanaJugador newframe =new VentanaJugador();
        //newframe.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;
        
        if (dinero >= 2000) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea comprar el mercado?", "Confirmación de compra", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
            ventJug.cantPlata-=2000;
            ventJug.cantMercado++;
         } else {
        // El jugador decidió no comprar 
    }
} else {
            this.insuficienteDinero("Mercado");
        }
        ventJug.setearLabels();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnComprarBombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarBombaActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;
        
        if (dinero >= 700) {
             int opcion = JOptionPane.showConfirmDialog(null, "¿Desea comprar la bomba?", "Confirmación de compra", JOptionPane.YES_NO_OPTION);
       if (opcion == JOptionPane.YES_OPTION) {
            ventJug.cantPlata-=700;
            ventJug.cantBomba++;
         } else {
        // El jugador decidió no comprar 
        }
    } else {
            this.insuficienteDinero("bomba");
        }
        ventJug.setearLabels();
    }//GEN-LAST:event_btnComprarBombaActionPerformed

    private void btnComprarBarcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarBarcosActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;
        
        if (dinero >= 2500) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea comprar el barco?", "Confirmación de compra", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            ventJug.cantBarcoF++;
            ventJug.cantPlata-=2500;
        } else {
        // El jugador decidió no comprar 
        }
    } else {
            this.insuficienteDinero("barco");
        }
        ventJug.setearLabels();
    }//GEN-LAST:event_btnComprarBarcosActionPerformed

    private void btnComprarCanonBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarCanonBBActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;
        
        if (dinero >= 900) {
             int opcion = JOptionPane.showConfirmDialog(null, "¿Desea comprar el cañon Barba Roja?", "Confirmación de compra", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
            ventJug.cantCanonBB++;
            ventJug.cantPlata-=900;
        } else {
        // El jugador decidió no comprar 
    }
} else {
            this.insuficienteDinero("cañón Barba Roja");
        }
        ventJug.setearLabels();
    }//GEN-LAST:event_btnComprarCanonBBActionPerformed

    private void btnComprarHierroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarHierroActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;
        
        if (dinero >= 5) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea comprar el hierro?", "Confirmación de compra", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
            ventJug.cantHierro++;
            ventJug.cantPlata-=5;
         } else {
        // El jugador decidió no comprar 
    }
} else {
    this.insuficienteDinero("hierro");
        }
        ventJug.setearLabels();
    }//GEN-LAST:event_btnComprarHierroActionPerformed

    private void btnComprarCanonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarCanonActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;    
        
        if (dinero >= 500) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea comprar el cañon?", "Confirmación de compra", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            ventJug.cantCanon++;
            ventJug.cantPlata-=500;
        }  else {
        // El jugador decidió no comprar 
    }
} else {
    this.insuficienteDinero("Cañon");
        }
    }//GEN-LAST:event_btnComprarCanonActionPerformed

    private void btnComprarCanonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarCanonMActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;      
        
        if (dinero >= 700) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea comprar el cañon múltiple?", "Confirmación de compra", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
            ventJug.cantCanonM++;
            ventJug.cantPlata-=700;
        } else {
        // El jugador decidió no comprar 
        }
    } else {
            this.insuficienteDinero("cañón múltiple");
        }
        ventJug.setearLabels();
    }//GEN-LAST:event_btnComprarCanonMActionPerformed

    private void btnComprarMinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarMinaActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata; 
        
        if (dinero >= 1000) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea comprar la mina?", "Confirmación de compra", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
            ventJug.cantMina++;
            ventJug.cantPlata-=1000;
         } else {
        // El jugador decidió no comprar 
        }
    } else {
            this.insuficienteDinero("mina");
        }
        ventJug.setearLabels();
    }//GEN-LAST:event_btnComprarMinaActionPerformed

    private void btnComprarTemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarTemploActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;  
        
        if (dinero >= 2500) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea comprar el templo de la bruja?", "Confirmación de compra", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            ventJug.cantTemplo++;
            ventJug.cantPlata-=2500;
        } else {
        // El jugador decidió no comprar 
        }
    } else {
            this.insuficienteDinero("templo de la bruja");
        }
        ventJug.setearLabels();
    }//GEN-LAST:event_btnComprarTemploActionPerformed

    private void btnComprarArmeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarArmeriaActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;  
        
        if (dinero >= 1500) {
          int opcion = JOptionPane.showConfirmDialog(null, "¿Desea comprar armería?", "Confirmación de compra", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            ventJug.cantArmeria++;
            ventJug.cantPlata-=1500;
        } else {
        // El jugador decidió no comprar 
        }
    } else {
            this.insuficienteDinero("armería");
        }
        ventJug.setearLabels();
    }//GEN-LAST:event_btnComprarArmeriaActionPerformed

    private void btnComprarFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarFuenteActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;

if (dinero >= 12000) {
    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea comprar la fuente de energía?", "Confirmación de compra", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
        ventJug.cantFuente++;
        ventJug.cantPlata-=1200;
    } else {
        // El jugador decidió no comprar 
    }
} else {
    this.insuficienteDinero("fuentes de energía");
}
    ventJug.setearLabels();
    }//GEN-LAST:event_btnComprarFuenteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;

if (dinero >= 500) {
    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea vender el cañón?", "Confirmación de compra", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
        ventJug.cantCanon--;
        ventJug.cantPlata+=500;
    } else {
        // El jugador decidió no vender
    }
} else {
    insuficienteProducto("cañón");
}

     ventJug.setearLabels();   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
int dinero = ventJug.cantPlata;

if (dinero >= 5) {
    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea vender el cañón?", "Confirmación de compra", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
        ventJug.cantHierro--;
        ventJug.cantPlata+=5;
    } else {
        // El jugador decidió no vender
    }
} else {
    this.insuficienteProducto("cañón");
}

     ventJug.setearLabels();   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;

if (dinero >= 2500) {
    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea vender el barco?", "Confirmación de venta", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
        ventJug.cantBarcoF--;
        ventJug.cantPlata+=2500;
    } else {
        // El jugador decidió no vender 
    }
} else {
    this.insuficienteProducto("Barco");
}

    ventJug.setearLabels();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;

if (dinero >= 700) {
    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea vender el cañon múltiple?", "Confirmación de venta", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
        ventJug.cantCanonM--;
        ventJug.cantPlata+=700;
    } else {
        // El jugador decidió no vender 
    }
} else {
    this.insuficienteProducto("Cañon Múltiple");
}

     ventJug.setearLabels();   
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;

if (dinero >= 700) {
    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea vender la bomba?", "Confirmación de venta", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
        ventJug.cantBomba--;
        ventJug.cantPlata+=700;
    } else {
        // El jugador decidió no vender 
    }
} else {
    this.insuficienteProducto("Bomba");
}
    ventJug.setearLabels();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;

if (dinero >= 900) {
    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea vender el cañon Barba Roja?", "Confirmación de venta", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
        ventJug.cantCanonBB--;
        ventJug.cantPlata+=900;
    } else {
        // El jugador decidió no vender 
    }
} else {
    this.insuficienteProducto("Cañon Barba Roja");
}
    ventJug.setearLabels();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;

if (dinero >= 1000) {
    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea vender la mina?", "Confirmación de venta", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
        ventJug.cantMina--;
        ventJug.cantPlata+=1000;
    } else {
        // El jugador decidió no vender 
    }
} else {
    this.insuficienteProducto("Mina");
}

    ventJug.setearLabels();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;

if (dinero >= 2500) {
    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea vender el templo de las brujas?", "Confirmación de venta", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
        ventJug.cantTemplo--;
        ventJug.cantPlata+=2500;
    } else {
        // El jugador decidió no vender 
    }
} else {
    this.insuficienteProducto("Templo de las Brujas");
}
     ventJug.setearLabels();   
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;

if (dinero >= 1500) {
    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea vender armería?", "Confirmación de venta", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
        ventJug.cantArmeria--;
        ventJug.cantPlata+=1500;
    } else {
        // El jugador decidió no vender 
    }
} else {
    this.insuficienteProducto("Armería");
}
    ventJug.setearLabels();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;

if (dinero >= 12000) {
    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea vender fuente de enería?", "Confirmación de venta", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
        ventJug.cantFuente--;
        ventJug.cantPlata+=1200;
    } else {
        // El jugador decidió no vender 
    }
} else {
    this.insuficienteProducto("Fuente de energía");
}
    ventJug.setearLabels();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        int dinero = ventJug.cantPlata;

if (dinero >= 2000) {
    int opcion = JOptionPane.showConfirmDialog(null, "¿Desea vender el mercado?", "Confirmación de venta", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
        ventJug.cantMercado--;
        ventJug.cantPlata+=2000;
    } else {
        // El jugador decidió no vender 
    }
} else {
    this.insuficienteProducto("Mercado");
}
    ventJug.setearLabels();
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMercado(new VentanaJugador()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarArmeria;
    private javax.swing.JButton btnComprarBarcos;
    private javax.swing.JButton btnComprarBomba;
    private javax.swing.JButton btnComprarCanon;
    private javax.swing.JButton btnComprarCanonBB;
    private javax.swing.JButton btnComprarCanonM;
    private javax.swing.JButton btnComprarFuente;
    private javax.swing.JButton btnComprarHierro;
    private javax.swing.JButton btnComprarMina;
    private javax.swing.JButton btnComprarTemplo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
